INSERT INTO Photo (property_id, url, caption, is_primary, sort_order) VALUES
(1, 'prop1_photo1.jpg', 'Living room with city view', 1, 1),
(1, 'prop1_photo2.jpg', 'Modern kitchen', 0, 2),
(2, 'prop2_photo1.jpg', 'Hollywood Hills vista', 1, 1),
(2, 'prop2_photo2.jpg', 'Infinity pool at sunset', 0, 2),
(3, 'prop3_photo1.jpg', 'Industrial loft space', 1, 1),
(4, 'prop4_photo1.jpg', 'Lakefront balcony', 1, 1),
(5, 'prop5_photo1.jpg', 'Cozy studio interior', 1, 1),
(6, 'prop6_photo1.jpg', 'Beachfront penthouse', 1, 1),
(6, 'prop6_photo2.jpg', 'Ocean view terrace', 0, 2),
(7, 'prop7_photo1.jpg', 'Downtown Seattle apartment', 1, 1),
(8, 'prop8_photo1.jpg', 'Historic brownstone facade', 1, 1),
(8, 'prop8_photo2.jpg', 'Classic interior', 0, 2),
(9, 'prop9_photo1.jpg', 'Mountain cabin exterior', 1, 1),
(10, 'prop10_photo1.jpg', 'Creative loft space', 1, 1),
(11, 'prop11_photo1.jpg', 'Beach house deck', 1, 1),
(12, 'prop12_photo1.jpg', 'Desert villa at dusk', 1, 1),
(13, 'prop13_photo1.jpg', 'Music Row apartment', 1, 1),
(14, 'prop14_photo1.jpg', 'Midtown Atlanta skyline', 1, 1),
(15, 'prop15_photo1.jpg', 'Riverwalk view', 1, 1),
(16, 'prop16_photo1.jpg', 'Historic loft interior', 1, 1);
