INSERT INTO BookingStatus (name, description) VALUES
('Pending', 'Booking request awaiting host approval'),
('Confirmed', 'Booking confirmed by host'),
('Cancelled', 'Booking has been cancelled'),
('Completed', 'Stay has been completed'),
('In Progress', 'Guest is currently staying'),
('Pending Payment', 'Awaiting payment confirmation'),
('Refunded', 'Booking refunded'),
('Declined', 'Host declined the booking'),
('Expired', 'Booking request expired'),
('Modified', 'Booking has been modified'),
('On Hold', 'Booking temporarily on hold'),
('Awaiting Review', 'Completed, awaiting guest review'),
('Under Review', 'Booking under admin review'),
('Payment Failed', 'Payment could not be processed'),
('Partially Refunded', 'Booking partially refunded'),
('No Show', 'Guest did not show up'),
('Early Checkout', 'Guest checked out early'),
('Extended', 'Stay was extended'),
('Dispute', 'Booking in dispute'),
('Archived', 'Old booking archived');
