INSERT INTO Wishlist (guest_id, property_id, notes) VALUES
(1, 2, 'Perfect for summer vacation'),
(2, 1, 'Consider for business trip'),
(3, 6, 'Dream beachfront property'),
(4, 8, 'Love the historic charm'),
(5, 13, 'Near music venues'),
(6, 11, 'Beach house for retreat'),
(7, 3, 'Great for long stay'),
(8, 14, 'Luxury option for anniversary'),
(9, 9, 'Mountain getaway'),
(10, 7, 'City location for shopping'),
(11, 19, 'Family vacation spot'),
(12, 4, 'Lakefront for summer'),
(13, 16, 'Historic district exploration'),
(14, 10, 'Creative space inspiration'),
(15, 12, 'Desert retreat'),
(16, 5, 'Cozy studio for weekend'),
(17, 17, 'Entertainment district stay'),
(18, 18, 'Lake cottage relaxation'),
(19, 15, 'Riverside peaceful stay'),
(20, 20, 'Urban loft experience');
