INSERT INTO PropertyType (name, description) VALUES
('Apartment', 'Self-contained housing unit in a building'),
('House', 'Standalone residential building'),
('Villa', 'Luxurious residential property'),
('Condo', 'Privately owned unit in a multi-unit building'),
('Townhouse', 'Multi-floor home sharing walls with neighbors'),
('Studio', 'Single-room living space'),
('Loft', 'Open-plan converted industrial space'),
('Cottage', 'Small house, typically in rural area'),
('Cabin', 'Rustic dwelling, often in woods'),
('Bungalow', 'Single-story house'),
('Penthouse', 'Luxury apartment on top floor'),
('Duplex', 'Two-unit residential building'),
('Guest House', 'Secondary accommodation on property'),
('Tiny House', 'Compact, minimalist dwelling'),
('Boat', 'Floating accommodation'),
('RV', 'Recreational vehicle accommodation'),
('Treehouse', 'Elevated structure built in trees'),
('Castle', 'Historic fortified residence'),
('Farm Stay', 'Accommodation on working farm'),
('Hostel', 'Budget shared accommodation');
