INSERT INTO Room (property_id, room_type, beds, capacity, name) VALUES
(1, 'Bedroom', 1, 2, 'Master Suite'),
(1, 'Bedroom', 2, 2, 'Guest Room'),
(2, 'Bedroom', 1, 2, 'Master Bedroom'),
(2, 'Bedroom', 1, 2, 'Second Bedroom'),
(2, 'Bedroom', 2, 2, 'Kids Room'),
(3, 'Bedroom', 1, 2, 'Loft Bedroom'),
(3, 'Living Area', 1, 2, 'Sofa Bed Area'),
(4, 'Bedroom', 1, 2, 'Master Suite'),
(4, 'Bedroom', 1, 2, 'Lake View Room'),
(5, 'Studio', 1, 2, 'Main Studio Space'),
(6, 'Bedroom', 1, 2, 'Master Suite'),
(6, 'Bedroom', 1, 2, 'Ocean View Room'),
(6, 'Bedroom', 1, 2, 'Sunset Room'),
(6, 'Bedroom', 2, 2, 'Twin Room'),
(7, 'Bedroom', 1, 2, 'Main Bedroom'),
(7, 'Bedroom', 1, 2, 'City View Room'),
(8, 'Bedroom', 1, 2, 'Master Bedroom'),
(8, 'Bedroom', 1, 2, 'Historic Room'),
(8, 'Bedroom', 2, 2, 'Garden Room'),
(9, 'Bedroom', 1, 2, 'Mountain View Room');
