INSERT INTO Amenity (name, icon, category) VALUES
('WiFi', 'wifi-icon.svg', 'Internet'),
('Free Parking', 'parking-icon.svg', 'Parking'),
('Air Conditioning', 'ac-icon.svg', 'Climate Control'),
('Heating', 'heat-icon.svg', 'Climate Control'),
('Kitchen', 'kitchen-icon.svg', 'Facilities'),
('Washer', 'washer-icon.svg', 'Laundry'),
('Dryer', 'dryer-icon.svg', 'Laundry'),
('TV', 'tv-icon.svg', 'Entertainment'),
('Workspace', 'desk-icon.svg', 'Work'),
('Pool', 'pool-icon.svg', 'Outdoor'),
('Hot Tub', 'hottub-icon.svg', 'Luxury'),
('Gym', 'gym-icon.svg', 'Fitness'),
('Elevator', 'elevator-icon.svg', 'Accessibility'),
('Fireplace', 'fireplace-icon.svg', 'Comfort'),
('Balcony', 'balcony-icon.svg', 'Outdoor'),
('Garden', 'garden-icon.svg', 'Outdoor'),
('BBQ Grill', 'grill-icon.svg', 'Outdoor'),
('Smoke Detector', 'smoke-icon.svg', 'Safety'),
('Carbon Monoxide Detector', 'co-icon.svg', 'Safety'),
('First Aid Kit', 'firstaid-icon.svg', 'Safety');
