CREATE TABLE Wishlist (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    guest_id INTEGER NOT NULL,
    property_id INTEGER NOT NULL,
    notes TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (guest_id) REFERENCES Guest(id) ON DELETE CASCADE,
    FOREIGN KEY (property_id) REFERENCES Property(id) ON DELETE CASCADE
);
